version: '3.6'

services:
  frontend:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true

