version: '3.6'

services:
  graphite:
    restart: always
    image: vladwing/graphite
    ports:
      - "2003:2003"
    volumes:
      - cnt_graphite:/opt/graphite/storage
    environment:
      - VIRTUAL_HOST=graphite.beia.cloud,graphite.beia-telemetrie.ro,graphite.beia-consult.ro
      - VIRTUAL_PORT=80
  grafana:
    restart: always
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-secret}
      - VIRTUAL_HOST=grafana.beia.cloud,grafana.beia-telemetrie.ro,grafana.beia-consult.ro
    volumes:
      - cnt_grafana:/var/lib/grafana
    depends_on:
      - graphite
  statsd:
    restart: always
    image: vladwing/statsd
    environment:
      - GRAPHITE_HOST=graphite
    depends_on:
      - graphite
    ports:
      - "8125:8125/udp"

volumes:
  cnt_graphite:
  cnt_grafana:
