version: '3.6'

services:
  graphite:
    image: vladwing/graphite
    volumes:
      - graphite:/opt/graphite/storage
      - graphite_conf:/opt/graphite/conf
    environment:
      VIRTUAL_HOST: 'graphite.beia.cloud,graphite.beia-telemetrie.ro,graphite.beia-consult.ro'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'graphite.beia-telemetrie.ro,graphite.beia-consult.ro'
      LETSENCRYPT_EMAIL: 'ssl-contact@beia.ro'
    networks:
     - graphite
     - proxy_net

  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - influxdb

  chronograf:
    image: chronograf
    deploy:
      replicas: 0
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
      VIRTUAL_HOST: 'chronograf.beia.cloud'
      VIRTUAL_PORT: 8888
    networks:
      - influxdb
      - proxy_net

  kapacitor:
    image: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    networks:
      - influxdb

  grafana:
    image: grafana/grafana:8.1.0
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: '/run/secrets/grafana_password'
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST__FILE: "/run/secrets/smtp_host"
      GF_SMTP_SKIP_VERIFY: "true"
      GF_SMTP_FROM_ADDRESS: "no-reply@beia-consult.ro"
      GF_SMTP_USER__FILE: '/run/secrets/smtp_user'
      GF_SMTP_PASSWORD__FILE: '/run/secrets/smtp_password'
      GF_SERVER_ROOT_URL: 'https://grafana.beia-telemetrie.ro'
      VIRTUAL_HOST: 'grafana.beia.cloud,grafana.beia-telemetrie.ro,grafana.beia-consult.ro'
      LETSENCRYPT_HOST: 'grafana.beia-telemetrie.ro,grafana.beia-consult.ro'
      LETSENCRYPT_EMAIL: 'ssl-contact@beia.ro'
    networks:
     - graphite
     - influxdb
     - proxy_net
    volumes:
      - grafana:/var/lib/grafana
    secrets:
      - grafana_password
      - smtp_user
      - smtp_password
      - smtp_host

  statsd:
    image: vladwing/statsd
    environment:
      GRAPHITE_HOST: 'graphite'
    networks:
     - graphite
     - statsd_net

  broker:
    image: beia/emqtt
    volumes:
      - emqtt_data:/opt/emqttd/data
      - emqtt_etc:/opt/emqttd/etc
      - emqtt_lib:/opt/emqttd/lib
      - emqtt_log:/opt/emqttd/log
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
        
    environment:
      EMQ_LOADED_PLUGINS: 'emq_recon,emq_modules,emq_retainer'
    networks:
     - broker
     - proxy_net

  # MQTT -- Graphite Midleware
  mqtt2graphite:
    image: beia/mqtt-to-graphite
    environment:
      - CARBON_SERVER=graphite
      # - CARBON_PORT=2003
      - MQTT_HOST=broker
      # -MQTT_PORT=1883
    networks:
     - broker
     - graphite

  mqtt2influxdb:
    image: beia/mqtt-to-graphite
    environment:
      - CARBON_SERVER=influxdb
      # - CARBON_PORT=2003
      - MQTT_HOST=broker
      # -MQTT_PORT=1883
    networks:
     - broker
     - influxdb

  lora2mqtt:
    image: beia/lora2mqtt
    environment:
      MQTT_HOST: 'broker'
      VIRTUAL_HOST: 'lora-aggregator.beia-telemetrie.ro'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'lora-aggregator.beia-telemetrie.ro'
      LETSENCRYPT_EMAIL: 'ssl-contact@beia.ro'
    networks:
     - proxy_net

volumes:
  emqtt_data:
  emqtt_etc:
  emqtt_lib:
  emqtt_log:
  graphite:
  graphite_conf:
  grafana:
  influxdb:
networks:
  graphite:
  broker:
  influxdb:
  statsd_net:
    external: true
  proxy_net:
    external: true
secrets:
  grafana_password:
    external: true
  smtp_user:
    external: true
  smtp_password:
    external: true
  smtp_host:
    external: true
