version: '3.6'

services:
  graphite:
    image: vladwing/graphite
    volumes:
      - graphite:/opt/graphite/storage
      - graphite_conf:/opt/graphite/conf
    environment:
      VIRTUAL_HOST: 'graphite.beia.cloud,graphite.beia-telemetrie.ro,graphite.beia-consult.ro'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'graphite.beia-telemetrie.ro,graphite.beia-consult.ro'
      LETSENCRYPT_EMAIL: 'ssl-contact@beia.ro'
    networks:
     - graphite
     - proxy_net

  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - influxdb

  chronograf:
    image: chronograf
    deploy:
      replicas: 0
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
      VIRTUAL_HOST: 'chronograf.beia.cloud'
      VIRTUAL_PORT: 8888
    networks:
      - influxdb
      - proxy_net

  kapacitor:
    image: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    networks:
      - influxdb

  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: '/run/secrets/grafana_password'
      VIRTUAL_HOST: 'grafana.beia.cloud,grafana.beia-telemetrie.ro,grafana.beia-consult.ro'
      LETSENCRYPT_HOST: 'grafana.beia-telemetrie.ro,grafana.beia-consult.ro'
      LETSENCRYPT_EMAIL: 'ssl-contact@beia.ro'
    networks:
     - graphite
     - influxdb
     - proxy_net
    volumes:
      - grafana:/var/lib/grafana
    secrets:
      - grafana_password

  statsd:
    image: vladwing/statsd
    environment:
      GRAPHITE_HOST: 'graphite'
    networks:
     - graphite
     - statsd_net

  iot-data:
    image: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - iot-data:/var/lib/postgresql/data
    networks:
      - graphite
    secrets:
      - postgres_password

  broker:
    image: beia/emqtt
    volumes:
      - emqtt_data:/opt/emqttd/data
      - emqtt_etc:/opt/emqttd/etc
      - emqtt_lib:/opt/emqttd/lib
      - emqtt_log:/opt/emqttd/log
    ports:
     - "1883:1883"
    environment:
      EMQ_LOADED_PLUGINS: 'emq_recon,emq_modules,emq_retainer'
    networks:
     - broker
     - proxy_net

  # MQTT -- Graphite Midleware
  mqtt2graphite:
    image: beia/mqtt-to-graphite
    environment:
      - CARBON_SERVER=graphite
      # - CARBON_PORT=2003
      - MQTT_HOST=broker
      # -MQTT_PORT=1883
    networks:
     - broker
     - graphite

  mqtt2influxdb:
    image: beia/mqtt-to-graphite
    environment:
      - CARBON_SERVER=influxdb
      # - CARBON_PORT=2003
      - MQTT_HOST=broker
      # -MQTT_PORT=1883
    networks:
     - broker
     - influxdb

  lora2mqtt:
    image: beia/lora2mqtt
    environment:
      MQTT_HOST: 'broker'
      VIRTUAL_HOST: 'lora.beia188.dfilip.xyz'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'lora.beia188.dfilip.xyz'
      LETSENCRYPT_EMAIL: 'dorinel@dfilip.xyz'
    networks:
     - proxy_net

  mqtt2postgres:
    image: vladwing/hang
    networks:
      - broker
      - graphite

volumes:
  emqtt_data:
  emqtt_etc:
  emqtt_lib:
  emqtt_log:
  graphite:
  graphite_conf:
  grafana:
  iot-data:
  influxdb:
networks:
  graphite:
  broker:
  influxdb:
  statsd_net:
    external: true
  proxy_net:
    external: true
secrets:
  postgres_password:
    external: true
  grafana_password:
    external: true
