THIS_MAKEFILE_PATH:=$(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST))
THIS_DIR:=$(shell cd $(dir $(THIS_MAKEFILE_PATH));pwd)
include $(THIS_DIR)/common.mak

STACK_FILE ?= stack.yml

deploy: predeploy create_network
	@$(DOCKER) stack deploy -c $(STACK_FILE) --prune $(STACK_NAME)

include $(STACK_SOURCE)
.PHONY: $(STACK_PREDEPLOY) create_network
predeploy: $(STACK_PREDEPLOY)

create_network:
	@$(THIS_DIR)/../scripts/create_network.sh $(CREATE_NETWORK)
