version: '3.6'

services:
  broker:
    image: beia/mqtt-broker
    volumes:
     - mosca_data:/db
    environment:
     - REDIS_HOST=redis
    ports:
     - "1883:1883"
    environment:
      VIRTUAL_HOST: mqtt.beia-consult.ro
      VIRTUAL_PORT: 80

  redis:
    image: redis:alpine
    volumes:
     - redis_data:/data

volumes:
  redis_data:
  mosca_data:
