version: "2"
services:
  citisim_app:
    container_name: citisim_app
    build: ./app
    links:
      - citisim_db
    ports:
      - "32100:80"

  citisim_db:
    image: mysql:5.7
    container_name: citisim_db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
