version: "2"
services:
  citisim_app:
    image: beia/citisim-webapp
    ports:
      - "32100:80"

  citisim_db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
