version: "2"
services:
  citisim_app:
    image: beia/citisim-webapp
    environment:
      VIRTUAL_HOST: 'smart-energy.beia-telemetrie.ro'
      LETSENCRYPT_HOST: 'smart-energy.beia-telemetrie.ro'
      LETSENCRYPT_EMAIL: 'ssl-contact@beia.ro'
    networks:
      - db
      - proxy_net

  citisim_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - db_data:/var/lib/mysql

networks:
  proxy_net:
    external: true
  db:

volumes:
  - db_data
